### ISSUE TITLE
Write a probram with a mother class animal. Inside it define a name and an age variables, and set_value() function.Then create two bases variables Zebra and Dolphin which write a message telling the age, the name and giving some extra information (e.g. place of origin).

### ISSUE THREAD

**Issue by mediocre9** [mediocre9/instruction#12]

**Comment by jamal1299** [comment]
Ok boss, I will start work from tomorrow first i will read your code than complete it

**Comment by jamal1299** [comment]
(Then create two bases variables Zebra and Dolphin which write a message telling the age, the name and giving some extra information (e.g. place of origin) 
Please elaborate this one statement.

**Comment by jamal1299** [comment]
Thank you !! I need to discusse some question about issue2

**Comment by jamal1299** [comment]
> 

**AMAZING**

**Comment by jamal1299** [comment]
> for learning purpose we will share code snippets to each other. for example we can also do it like this.
> 
> ```js
> class Animal{
> 
>     setValues(name ,age, info){
>         this.name = name;
>         this.age = age;
>         this.info = info;
>         return this;
>     }
>             
>     showValues() {
>         console.log(`I am ${this.name} My age is ${this.age} and i am from ${this.info}`);
>     }
> }
>         
>         
> let zebra = new Animal();
> 
> zebra.setValues("zebra", 5, "madagascar")
>       .showValues();
> ```
> 
> i am still learning javascipt 😅

hahah No bro You are Pro

**Comment by jamal1299** [comment]
> > **AMAZING**
> 
> Thanks ❤️ 😍
> 
> **Protip:**
> 
> if you want to share code snippet just like i did.
> 
> follow this docs link . . . [Syntax Highlighting](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks)

Thanks <3

**Comment by jamal1299** [comment]
```ruby
class Animal{

    setValues(name ,age, info){
        this.name = name;
        this.age = age;
        this.info = info;
        return this;
    }
            
    showValues() {
        console.log(`I am ${this.name} My age is ${this.age} and i am from ${this.info}`);
    }
}
        
        
let zebra = new Animal();

zebra.setValues("zebra", 5, "madagascar")
      .showValues();
```

**Comment by jamal1299** [comment]
class Animal{

    setValues(name ,age, info){
        this.name = name;
        this.age = age;
        this.info = info;
        return this;
    }
            
    showValues() {
        console.log(`I am ${this.name} My age is ${this.age} and i am from ${this.info}`);
    }
}
        
        
let zebra = new Animal();

zebra.setValues("zebra", 5, "madagascar")
      .showValues();

**Comment by jamal1299** [comment]
Testing...

**Comment by jamal1299** [comment]
```English
  let understand= 100%;
```

**Comment by jamal1299** [comment]
```ruby
let understand = 100%;
```
