### ISSUE TITLE
 Create a class named Pizza that stores information about a single pizza.

### ISSUE THREAD

**Issue by mediocre9** [mediocre9/instruction#17]
### It should contain the following:  
1. Private  instance  variables  to  store  the  size  of  the  pizza  (either  small,  medium, or large), the  number of  cheese toppings, the number of pepperoni toppings, and the number of ham toppings. 
2. Constructor(s) that set all of the instance variables. 
3. Public methods to get and set the instance variables. 
4.   A public method named calcCost( ) that returns a double that is the cost of the pizza. Pizza cost is determined by: Small: $10 + $2 per topping Medium: $12 + $2 per topping Large: $14 + $2 per topping  
5.  public method named getDescription( ) that returns a String containing the pizzasize, quantity of each topping.

**Comment by jamal1299** [comment]
Hi, 
I readed all the issues and the first issue which was the **solve real problem** so i will disscuss this issue in uni and for now i will start this issue to solve it.
Thank You

**Comment by jamal1299** [comment]
```JAVASCRIPT
    <script>
        class Pizza {

            // Private Instance 
            #Pizza_size;
            #No_of_cheese;
            #No_of_pepperoni;
            #No_of_ham;

            constructor(Pizza_size, No_of_cheese, No_of_pepperoni, No_of_ham) {
                this.#Pizza_size = Pizza_size;
                this.#No_of_cheese = No_of_cheese;
                this.#No_of_pepperoni = No_of_pepperoni;
                this.#No_of_ham = No_of_ham;


            }

            calculateCost(Pizza_size) {
                switch (Pizza_size) {
                    case 'small':
                        console.log(' $10 + $2 per topping');
                        break;

                    case 'medium':
                        console.log(' $12 + $2 per topping');
                        break;

                    case 'large':
                        console.log(' $14 + $2 per topping');
                        break;

                    default: {
                        console.log('Please Check Your Input ! Make Sure You Entered "small or medium or large "');
                        break;

                    }
                }


            }

            getDescription() {
                console.log(` Pizza Size : ${this.#Pizza_size} \n No of Cheese Topping ${this.#No_of_cheese} \n No of Pepperoni topping : ${this.#No_of_pepperoni} \n No of ham ${this.#No_of_ham}`);
            }

            get getData() {
                this.#Pizza_size;
                this.#No_of_cheese;
                this.#No_of_pepperoni;
                this.#No_of_ham;
                return this;

            }

            // Setter is Not Implemented because set method accept one value can you please implement the setter.


        }

        let obj = new Pizza('Small', 2, 3, 4);



    </script>

```

**Comment by mediocre9** [comment]
> ```JAVASCRIPT
>     <script>
>         class Pizza {
> 
>             // Private Instance 
>             #Pizza_size;
>             #No_of_cheese;
>             #No_of_pepperoni;
>             #No_of_ham;
> 
>             constructor(Pizza_size, No_of_cheese, No_of_pepperoni, No_of_ham) {
>                 this.#Pizza_size = Pizza_size;
>                 this.#No_of_cheese = No_of_cheese;
>                 this.#No_of_pepperoni = No_of_pepperoni;
>                 this.#No_of_ham = No_of_ham;
> 
> 
>             }
> 
>             calculateCost(Pizza_size) {
>                 switch (Pizza_size) {
>                     case 'small':
>                         console.log(' $10 + $2 per topping');
>                         break;
> 
>                     case 'medium':
>                         console.log(' $12 + $2 per topping');
>                         break;
> 
>                     case 'large':
>                         console.log(' $14 + $2 per topping');
>                         break;
> 
>                     default: {
>                         console.log('Please Check Your Input ! Make Sure You Entered "small or medium or large "');
>                         break;
> 
>                     }
>                 }
> 
> 
>             }
> 
>             getDescription() {
>                 console.log(` Pizza Size : ${this.#Pizza_size} \n No of Cheese Topping ${this.#No_of_cheese} \n No of Pepperoni topping : ${this.#No_of_pepperoni} \n No of ham ${this.#No_of_ham}`);
>             }
> 
>             get getData() {
>                 this.#Pizza_size;
>                 this.#No_of_cheese;
>                 this.#No_of_pepperoni;
>                 this.#No_of_ham;
>                 return this;
> 
>             }
> 
>             // Setter is Not Implemented because set method accept one value can you please implement the setter.
> 
> 
>         }
> 
>         let obj = new Pizza('Small', 2, 3, 4);
> 
> 
> 
>     </script>
> 
> ```

Perfect... Though you had to set thos values separately setPizzaSize(argument ), setNoOfCheese() and so on... Then return this values getPizzaSize(), getNoOfCheese()..... It is a good effort you have followed all the rules but always use camelCase or snake_case for variables

**Comment by jamal1299** [comment]
Oh got it sir, 
Ex: for every instance will be seperate setter.

**Comment by jamal1299** [comment]
About variable : pizza_size pizzaSize 
Suggest me which one i use in these both

**Comment by mediocre9** [comment]
Yes, Setter and getter

**Comment by mediocre9** [comment]
Follow any style be but you should be consistent.... Personally i prefer camelCase...

**Comment by jamal1299** [comment]
Thank you

**Comment by mediocre9** [comment]
```javascript
get getData() { 
       this.#Pizza_size; 
        this.#No_of_cheese;                              this.#No_of_pepperoni; this.#No_of_ham; 
return this; 
} 
```


This method code is redundant just read the code.... You could only have done it like this... It would give you acces to all the fields... 

```javascript
get getData() {
return this; 
} 
```

**Comment by jamal1299** [comment]
It will return the class ? Is i am right?

**Comment by jamal1299** [comment]
I try to return only specific instances but I think for that i need to create specific getter.

**Comment by mediocre9** [comment]
> It will return the class ? Is i am right? 

It will return the object.

**Comment by jamal1299** [comment]
> > It will return the class ? Is i am right? 
> 
> It will return the object. 

Ok got it

**Comment by mediocre9** [comment]
> I try to return only specific instances but I think for that i need to create specific getter.

Look you are only just writing this. #variable; then you are returning the object afterwards it makes no sense... Means interpreter will just read that code but wont do anything

**Comment by mediocre9** [comment]
> I try to return only specific instances but I think for that i need to create specific getter.

Yes separate getter for all members..

**Comment by jamal1299** [comment]
Ok ok ! In sha allah tomorrow we will discuss getter and setter in uni because i am little-bit confuse in it.

**Comment by mediocre9** [comment]
Sure...overall you are doing a great job.. Keep it up.. MashAllah

**Comment by mediocre9** [comment]
Though i have released vision's build after 6 months.. You can download and test it... And can give review about it.

**Comment by jamal1299** [comment]
Thanks fahad it's all your efforts.

**Comment by jamal1299** [comment]
> months

**Amazing**, why not dear

**Comment by mediocre9** [comment]
> Thanks fahad it's all your efforts.

Nah you're just being humble its your dedication that is paying off i am just a guide or friend helper.. 😄

**Comment by Jawad-wakeel** [comment]
Hi
I'm learning the syntax of oop in javascript, it's similar to c++ oop syntax, but some of little syntax need to learn....

**Comment by mediocre9** [comment]
> Hi
> I'm learning the syntax of oop in javascript, it's similar to c++ oop syntax, but some of little syntax need to learn.... 

Ok

**Comment by Jawad-wakeel** [comment]
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Pizza</title>
</head>
<body style="display: flex; align-items: center; justify-content: center; height: 100vh">
	
</body>
<script>

	class Pizza{
		pizza_size;
		no_chees_topping;
		no_peperoni_topping;
		no_ham_topping;
		cost;
		constructor(){
			this.pizza_size = 'NULL';
			this.no_chees_topping = 0;
			this.no_peperoni_topping = 0;
			this.no_ham_topping = 0;
			this.cost = 0.0;
		} 

		setOrder(size, cheesTopping, peproniTopping, hamTopping){
			this.pizza_size = size;
			this.no_chees_topping = cheesTopping;
			this.no_peperoni_topping = peproniTopping;
			this.no_ham_topping = hamTopping;
		} 

		//Set method to set the instance of variable 

		setPizzaSize(size){
			this.pizza_size = size;
		}
		setNoOfCheesTopping(cheesTopping){
			this.no_chees_topping = cheesTopping;
		}
		setNoOfPeproniTopping(peproniTopping){
			this.no_peperoni_topping = peproniTopping;
		}
		setNoOfHamTopping(hamTopping){
			this.no_ham_topping = hamTopping;
		}

		//get method to get the instance of variable

		getPizzaSize(){
			return this.pizza_size;
		}
		getNoOfCheesTopping(){
			return this.no_chees_topping;
		}
		getNoOfPeproniTopping(){
			return this.no_peperoni_topping;
		}
		getNoOfHamTopping(){
			return this.no_ham_topping;
		}



		getDescription(){
			console.log("You ordered " + this.getPizzaSize() + " size of Pizza Quantity of chees topping " + this.getNoOfCheesTopping() + ", Peperono topping " + this.getNoOfPeproniTopping() + ", Ham topping " + this.getNoOfHamTopping() + ".")
		}



		//methos to calculate total cost
		calcCost(){
			switch(this.getPizzaSize()){
				case 'small':
					 return this.cost = 10 + 2*(this.getNoOfCheesTopping() + this.getNoOfPeproniTopping() + this.getNoOfHamTopping());
					 break;
				case 'medium':
					return this.cost = 12 + 2*(this.getNoOfCheesTopping() + this.getNoOfPeproniTopping() + this.getNoOfHamTopping());
					break;
				case 'large':
					return this.cost = 14 + 2*(this.getNoOfCheesTopping() + this.getNoOfPeproniTopping() + this.getNoOfHamTopping());
					break;
				default:
					console.log("enter correct");
			}
		}


	};

		obj = new Pizza();
		obj.setOrder('small', 5 , 5, 2);
		obj.getDescription();
		let totalCost = obj.calcCost();
		console.log("\nTotal cost is : " + totalCost + "$")



</script>
</html>

**Comment by Jawad-wakeel** [comment]
I've done it..

**Comment by jamal1299** [comment]
**Amazing **

**Comment by mediocre9** [comment]
**Welldone**
