### ISSUE TITLE
Write a class for email and password validator.

### ISSUE THREAD

**Issue by mediocre9** [mediocre9/instruction#19]
1. All member variables and methods should be static.
2. `validateEmail` for setting up static member email variable and return type should be `boolean`.
3. `validatePassowrd` for setting up static member password variable and return type should be `boolean`.
5. your logic methods should be abstracted away from above methods and they also should be private static methods.

### _GUI is not allowed._

**Comment by mediocre9** [comment]
Excellent work.....

**Comment by jamal1299** [comment]
Thank you ❤️
